apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: isabellagoncalves
spec:
  selector:
    app: frontend-container-isabellagoncalves
  ports:
    - protocol: TCP
      port: 52032
      targetPort: 52032
  type: ClusterIP
