apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-isabellagoncalves
  namespace: isabellagoncalves
spec:
  storageClassName: default-storage-class-isabellagoncalves
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: isabellagoncalves
